### PR TITLE
fix syntax errors if running in linux shell

### PR DESCRIPTION
**Pull request by mindcrime-ilab**
Fix errors executing the boot scripts on Linux.

    pivio.sh: 35: [: Linux: unexpected operator
    pivio.sh: 68: pivio.sh: Syntax error: "(" unexpected

### CODE REVIEW

**Comment by marthjod** [comment]
-1.

Replacing double equals with one is just bad form and they are not the problem cause.
The commit message is misleading: This runs fine on "Linux". The mistake here is using Bash-isms (array syntax etc.) when having declared a /bin/sh she-bang. This probably worked on the authors' machine because some systems use /bin/bash as stand-in for /bin/sh.

**Comment by mindcrime-ilab** [comment]
I do not know why it should be "just bad form" - if using sh (which is dash on my system) does not allow double equals syntax.

**Comment by fmueller** [comment]
@oliverwehrens Can you give your 2 cents on this, please?

**Comment by oliverwehrens** [comment]
I have this running on MacOS and CentOS 7 Linux. At least on these system it works with /bin/sh (which is not symlinked or anything to any other shell). @mindcrime-ilab Why is /bin/sh dash on your system? I have no way in reproducing the error. Which distribution are your running?

**Comment by mindcrime-ilab** [comment]
I run Ubuntu 16.10 without active changes to the environment (https://wiki.ubuntu.com/DashAsBinSh). Seems to be standard to in Ubuntu provide dash as default shell. Just tried again to be sure:


    /tmp$ git clone https://github.com/pivio/pivio-boot.git
    Cloning into 'pivio-boot'...
    remote: Counting objects: 44, done.
    remote: Compressing objects: 100% (7/7), done.
    remote: Total 44 (delta 1), reused 0 (delta 0), pack-reused 37
    Unpacking objects: 100% (44/44), done.
    Checking connectivity... done.
    /tmp$ cd pivio-boot/
    /tmp/pivio-boot$ ./pivio.sh 
    ./pivio.sh: 35: [: Linux: unexpected operator
    ./pivio.sh: 68: ./pivio.sh: Syntax error: "(" unexpected

Running with my version of the sh script works fine on my machine - but this should not be that interesting. I think it should conform the POSIX spec. As far as I understand the POSIX this syntax (single equal) is specification complaint (http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html) and the only legal form - maybe I have a misunderstanding here.

**Comment by bhelfert** [comment]
_dash_, the _Debian Almquist SHell_, is the default shell of Debian (since 6, Sqeeze) and Ubuntu (since 6.10). So I guess, @mindcrime-ilab is using one of those and we can use it to reproduce/fix the errors. I assume (e.g. as a quick fix) we could just use `#!/bin/bash` instead of `#!/bin/sh` in the pivio-boot shell scripts. I will try that. However, we should think about making the scripts Bourne Shell / POSIX compliant.

BTW, to determine to which default shell /bin/sh is symlinked on your machine use:
`ls -l "$(which sh)"`

To find out the shell of the user you are logged in with run:
`grep -- "$LOGNAME" /etc/passwd | awk -F":" '{print $7}'`

Some additional background info:
- [Comparision table of Bourne-compatible shells](https://rosettacode.org/wiki/Category:UNIX_Shell_Implementations) (a bit outdated but a start)
- [Ubuntu: dash as /bin/sh](https://wiki.ubuntu.com/DashAsBinSh)

**Comment by bhelfert** [comment]
PR tested with CentOS 7 (bash), Debian 8 (dash), and Ubuntu 14 (dash).

**Pull request merged**
